### ISSUE TITLE
Write the definition of a void function with reference parameter of type tourType to input in a variable of type tourType

### ISSUE THREAD

**Issue by ayo-dami** [ayo-dami/SDI#7]

**Comment by ayo-dami** [comment]
#include "stdafx.h"
#include <iostream>
#include <string>
#include <fstream>

using namespace std;
struct timeType
{
	int hr, sec;
	double min;
};

struct tourType
{
	string cityName, county, country;
	int distance;
	timeType travelTime;
};

void extrainfo(tourType);


int main()
{
	
	tourType destination;
	destination.cityName = ("Nottingham");
	destination.distance = 130;
	destination.travelTime.hr = 3;
	destination.travelTime.min = 15;
	destination.travelTime.sec = 0;

	cout << "City Name: " << destination.cityName << "\n";
	cout << "Distance: " << destination.distance << "\n";
	cout << "Time: " << destination.travelTime.hr << "hr " << destination.travelTime.min << "minute(s) " << destination.travelTime.sec << "second(s)" << "\n\n";
	cout << "Please Enter a county: ";
	cin >> destination.county;
	cout << "County: " << destination.county << "\n\n";
	extrainfo(destination);

    return 0;
}

void extrainfo(tourType destination) {
	
	string country;

	cout << "Please Enter a country: ";
	cin >> destination.country;
	cout << "Country: " << destination.country << "\n\n";

}

**Comment by petrindade** [comment]
Good to know this exercise has been completed. Keep up the good work!
